# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    java -jar codacy-coverage-reporter-assembly-0.0.1-SNAPSHOT.jar report --project-token 123
    git log | echo
    echo 'HERE'$(Build.SourceVersion)'HERE'
    echo 'HERE2'$TF_BUILD'HERE2'
  displayName: 'Run a multi-line script'
